# astype()

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
arr_1=arr.astype(np.float32)
print(arr,"----->",arr.dtype)
print(arr_1,"----->",arr_1.dtype)

[1 2 3 4] -----> int64
[1. 2. 3. 4.] -----> float32


In [8]:
a=np.array([1,2,3,4,"hello"])
print(a)
print(a.dtype)

['1' '2' '3' '4' 'hello']
<U21


# random numbers

### np.random.rand()

In [12]:
print(np.random.rand())
print("---------------")

#1d array of 5 random elements
print(np.random.rand(5))
print("---------------")
#2d array (5rows,4coloumns)
print(np.random.rand(5,4))


0.7970522415400636
---------------
[0.43910539 0.72156174 0.99110082 0.4674544  0.3368772 ]
---------------
[[0.43986065 0.73196882 0.30060382 0.61795285]
 [0.05811201 0.29063823 0.94778493 0.87613135]
 [0.87797974 0.92108665 0.36265385 0.77018763]
 [0.97771987 0.7726927  0.53857021 0.81525185]
 [0.15048186 0.73103987 0.50536019 0.30794529]]


### np.random.randn()

In [13]:
print(np.random.randn())
print("---------------")

#1d array of 5 random elements
print(np.random.randn(5))
print("---------------")
#2d array (5rows,4coloumns)
print(np.random.randn(5,4))


0.706035541559022
---------------
[-0.95877774  0.75006749  0.55785034 -0.70291883 -0.45994384]
---------------
[[ 1.4074932  -2.27381358  0.48862195 -1.51268974]
 [-0.55223632 -0.71805937 -0.62368268 -0.45549629]
 [ 0.60442447  0.13432885 -0.68688425  2.00430952]
 [-0.23544692 -0.47618088  0.84946693  1.866575  ]
 [ 0.99942682 -0.51106504  0.84157037 -0.75789813]]


### np.random.randint(start,stop)

In [14]:
a=np.random.randint(1,10,size=5) #randomly generate 1to9 no.of elments:5
print(a)
a=np.random.randint(1,10,size=(5,6))
print(a)

[2 7 3 4 4]
[[9 1 9 3 8 1]
 [5 9 8 3 1 9]
 [5 3 3 3 4 6]
 [7 9 6 9 2 3]
 [3 9 2 9 6 2]]


### np.random.uniform(start,stop)

In [15]:
a=np.random.uniform(1,10,size=5) #randomly generate decimal numbers 1to9 no.of elments:5
print(a)
a=np.random.uniform(1,10,size=(5,6))
print(a)

[1.58304047 4.9482246  3.66307195 7.37231993 6.51438847]
[[2.14632157 8.12233445 5.55395096 9.88953492 7.75220117 8.57298763]
 [4.90135005 2.66403008 3.43767406 6.69772127 2.77697029 6.00028668]
 [6.54915481 6.18411118 5.94878117 5.58204623 1.22631498 1.52087759]
 [4.74071428 2.48892163 5.88858052 5.2482939  1.82483782 2.89330901]
 [5.86562621 8.46027416 8.13373925 6.49345729 3.95441362 5.2771091 ]]


# indexing in numpy

In [21]:
#1d array
arr=np.array([1,2,3,4])
print(arr)
print("---------------")
print(arr[0])
print(arr[1])
print(arr[2])
print("---------------")
print(arr[-1])
print(arr[-3])
print(arr[-2])

[1 2 3 4]
---------------
1
2
3
---------------
4
2
3


# slicing

In [31]:
arr=np.array([1,2,3,4])
print(arr)
print("---------------")
print(arr[0:5])
print(arr[0:5:2])
print(arr[::-1])

[1 2 3 4]
---------------
[1 2 3 4]
[1 3]
[4 3 2 1]


## 2d arrayindexing in numpy

In [30]:
# 2d arrayindexing in numpy
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print(arr[0,3])
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])
print(arr[1,3])
print(arr[2,0])
print(arr[2,1])
print(arr[2,2])
print(arr[2,3])
print("---------------")
print(arr[-1,-1])
print(arr[-1,-2])
print(arr[-1,-3])
print(arr[-1,-4])
print(arr[-2,-1])
print(arr[-2,-2])
print(arr[-2,-3])
print(arr[-2,-4])
print(arr[-3,-1])
print(arr[-3,-2])
print(arr[-3,-3])
print(arr[-3,-4])


1
2
3
4
5
6
7
8
9
10
11
12
---------------
12
11
10
9
8
7
6
5
4
3
2
1


## 2d array slicing

In [40]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(arr[0,:]) #extract 1 row
print(arr[1,:]) #extract 2 row
print(arr[2,:]) #extract 3row
print("---------------")
print(arr[:,0]) #extract 1 column
print(arr[:,1]) #extract 2 column
print(arr[:,2]) #extract 3 column
print("---------------")
print(arr[0:2,:]) #extract first 2 rows
print("---------------")
print(arr[0:2,0:2]) 
print("---------------")
print(arr[:,1:3]) 
print("---------------")
print(arr[1:3,:]) 

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
---------------
[1 5 9]
[ 2  6 10]
[ 3  7 11]
---------------
[[1 2 3 4]
 [5 6 7 8]]
---------------
[[1 2]
 [5 6]]
---------------
[[ 2  3]
 [ 6  7]
 [10 11]]
---------------
[[ 5  6  7  8]
 [ 9 10 11 12]]


## boolean indexing

In [42]:
arr=np.array([1,2,3,4,5,6])
con=arr>3
print(con)
print(arr[con])

[False False False  True  True  True]
[4 5 6]


In [43]:
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])

[4 5 6]


In [46]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
print(arr>5)
print(arr[arr>5])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


## updating numpy

In [49]:
arr=np.array([1,2,3,4,5,6])
#updating single element
arr[0]=20
#updating multiple element
arr[1:3]=30,40
print(arr)
#updating multiple element using boolean indexing
arr[arr>4]=50
print(arr)

[20 30 40  4  5  6]
[50 50 50  4 50 50]


## fancy indexing

In [50]:
arr=np.array([1,2,3,4,5,6])
arr[[2,3,5]]=[10,30,40]
print(arr)


[ 1  2 10 30  5 40]


## updating numpy 2d array

In [66]:
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
#update single element
arr[0,0]=10
print(arr)
print("---------------")
#updating entire row
arr[1]=[1,2,3,4]
print(arr)
print("---------------")
arr[0:2,0:2]=[[1,2],
               [3,4]]

print("---------------")
#update entire column
arr[:,3]=[11,12,13]
print(arr)
print("---------------")
# fancy indexing
arr[[2,2],[0,3]]=[1000,1200]#-->(2,0),and (2,3)
print(arr)
print("---------------")
#boolean indexing
arr[arr>800]=900
print(arr)

[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------
[[10  2  3  4]
 [ 1  2  3  4]
 [ 9 10 11 12]]
---------------
---------------
[[ 1  2  3 11]
 [ 3  4  3 12]
 [ 9 10 11 13]]
---------------
[[   1    2    3   11]
 [   3    4    3   12]
 [1000   10   11 1200]]
---------------
[[  1   2   3  11]
 [  3   4   3  12]
 [900  10  11 900]]


#  update using negative indexing 

In [75]:
arr=np.array([[1,2,3],
             [5,6,7],
             [9,10,11]])
arr[-2:,-2:]=[[10,20],
              [50,90]]
print(arr)
arr[-3:-1,-3:-1]=[[10,20],
              [50,90]]
print(arr)

[[ 1  2  3]
 [ 5 10 20]
 [ 9 50 90]]
[[10 20  3]
 [50 90 20]
 [ 9 50 90]]


In [ ]:
arr=np.array([[1,2,3],
             [5,6,7],
             [9,10,11]])
arr[-3:-1,-3:-1]=[[10,20],
              [50,90]]
print(arr)