## logical operator

In [2]:
import numpy as np

In [7]:
a=np.array([10,20,30,40])
print(np.logical_and(a>15,a<35))
print(np.logical_or(a<15,a>35))
print(np.logical_not(a>25))

[False  True  True False]
[ True False False  True]
[ True  True False False]


## Assignment operator

In [13]:
a=np.array([10,20,30])
a+=5
print(a)
a-=5
print(a)
a*=2
print(a)
a//=2
print(a)
a%=4
print(a)
a**=2
print(a)
#a/=5----->it shows error,because of it is difeerent datatype
#print(a)

[15 25 35]
[10 20 30]
[20 40 60]
[10 20 30]
[2 0 2]
[4 0 4]


In [14]:
a=np.array([10.,20.,30.])
a/=5
print(a)

[2. 4. 6.]


# Numpy maths

### sqrt()

In [16]:
import math
numbers=[4,9,16,25]
b=[math.sqrt(i) for i in numbers]
print(b)

[2.0, 3.0, 4.0, 5.0]


In [17]:
a=np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [18]:
arr2d=np.array([[4,9],
               [16,25]])
print(np.sqrt(arr2d))

[[2. 3.]
 [4. 5.]]


# exp()

In [19]:
print(math.exp(1))
print(math.exp(2))

2.718281828459045
7.38905609893065


In [21]:
a=np.array([0,1,2,3,4])
re=np.exp(a)
print(re)

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [22]:
arr2d=np.array([[1,2],
               [3,4]])
re=np.exp(arr2d)
print(re)

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


## sin,cos

In [26]:
angles_deg=np.array([0,20,45,90])

#convert degrees toradians
angles_rad=np.deg2rad(angles_deg)
print("degrees:",angles_deg)
print("radians:",angles_rad)

#sin value
sin_val=np.sin(angles_rad)
print("sin value:",sin_val)

degrees: [ 0 20 45 90]
radians: [0.         0.34906585 0.78539816 1.57079633]
sin value: [0.         0.34202014 0.70710678 1.        ]


In [27]:
angles_deg=np.array([[0,20],
                    [45,90]])
angles_rad=np.deg2rad(angles_deg)
print("degrees:",angles_deg)
print("radians:",angles_rad)

#sin value
sin_val=np.sin(angles_rad)
print("sin value:",sin_val)

#cos value
cos_val=np.cos(angles_rad)
print("cos value:",cos_val)

degrees: [[ 0 20]
 [45 90]]
radians: [[0.         0.34906585]
 [0.78539816 1.57079633]]
sin value: [[0.         0.34202014]
 [0.70710678 1.        ]]
cos value: [[1.00000000e+00 9.39692621e-01]
 [7.07106781e-01 6.12323400e-17]]


In [28]:
angles=np.array([0,np.pi/4,np.pi/3,np.pi/2])
cos_val=np.cos(angles)
print("degrees:",angles)
print("cos value:",cos_val)

degrees: [0.         0.78539816 1.04719755 1.57079633]
cos value: [1.00000000e+00 7.07106781e-01 5.00000000e-01 6.12323400e-17]


## Add()

In [34]:
a=np.array([1,2])
b=np.array([3,4])
print(np.add(a,b))#--->it takes only two arguments

[4 6]


In [30]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

print(np.add(a,b))

[[ 6  8]
 [10 12]]


## Subtract()

In [31]:
a=np.array([1,2])
b=np.array([3,4])
print(np.subtract(a,b))

[-2 -2]


In [33]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

print(np.subtract(a,b))

[[-4 -4]
 [-4 -4]]


## multiply

In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.multiply(a,b))

[ 4 10 18]


In [36]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

print(np.multiply(a,b))

[[ 5 12]
 [21 32]]


## division() or divide()

In [37]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [40]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

print(np.divide(b,a))

[[5.         3.        ]
 [2.33333333 2.        ]]


## dot poduct()

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


In [43]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])

print(np.dot(a,b))

[[19 22]
 [43 50]]


## @operator

In [44]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a@b#------> it's perform dot product
print(c)

32


In [45]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[5,6],
            [7,8]])
c=a@b
print(c)

[[19 22]
 [43 50]]


# numpy statistics

## sum()

In [48]:
arr=np.array([1,2,3,4,5])
total=np.sum(arr)
print(total)

15


In [54]:
a=np.array([[1,2,3],
            [4,5,6]])
total=np.sum(a)
print(total)

#sum of rows
print("sum of rows:",np.sum(a,axis = 1))
print("sum of coloumns:",np.sum(a,axis=0))

21
sum of rows: [ 6 15]
sum of coloumns: [5 7 9]


## min()

In [55]:
arr=np.array([1,2,3,4,5])
minimum=np.min(arr)
print(minimum)

1


In [57]:
a=np.array([[1,2,3],
            [4,5,6]])
minimum=np.min(a)
print(minimum)
print("minimum of rows:",np.min(a,axis = 1))
print("minimum of coloumns:",np.min(a,axis=0))

1
minimum of rows: [1 4]
minimum of coloumns: [1 2 3]


## max()

In [58]:
arr=np.array([1,2,3,4,5])
maximum=np.max(arr)
print(maximum)

5


In [59]:
a=np.array([[1,2,3],
            [4,5,6]])
maximum=np.max(a)
print(maximum)
print("maximum of rows:",np.min(a,axis = 1))
print("maximum of coloumns:",np.min(a,axis=0))

6
maximum of rows: [1 4]
maximum of coloumns: [1 2 3]
