# numpy broadcasting

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4],
            [2,4,5,6],
            [10,20,30,40]])
b=np.array([2,4,6,8])
print(a)
print(a.shape)
print("--"*10)
print(b)
print(b.shape)
print("--"*10)
print(a+b)
print("--"*10)
print(a-b)
print("--"*10)
print(a*b)
print("--"*10)
print(a/b)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 30 40]]
(3, 4)
--------------------
[2 4 6 8]
(4,)
--------------------
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 36 48]]
--------------------
[[-1 -2 -3 -4]
 [ 0  0 -1 -2]
 [ 8 16 24 32]]
--------------------
[[  2   8  18  32]
 [  4  16  30  48]
 [ 20  80 180 320]]
--------------------
[[0.5        0.5        0.5        0.5       ]
 [1.         1.         0.83333333 0.75      ]
 [5.         5.         5.         5.        ]]
--------------------


In [5]:
arr1=np.arange(15).reshape(5,3)
print(arr1)
print("--"*10)
arr2=np.arange(5).reshape(5,1)
print(arr2)
print("--"*10)
print(arr1+arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
--------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
--------------------
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [6]:
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
print(a)
print("--"*10)
b=a.T #trnspose
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
a=np.array(["apple","banana","grape","orange"])
print(a)
print(a.dtype)

['apple' 'banana' 'grape' 'orange']
<U6


In [9]:
a=np.array([["welcome"],
            ["hi"]])
print(a)

[['welcome']
 ['hi']]


In [10]:
print(np.char.add(["welcome"],["hi"]))

['welcomehi']


In [11]:
a=np.array(["hello"," "])
b=np.array(["world","numpy"])
result=np.char.add(a,b)
print(result)

['helloworld' ' numpy']


# Rounding function()

### 1.round()

In [12]:
a=np.array([3.2,3.6,7.89,3.5,2.58])
print(np.round(a))

[3. 4. 8. 4. 3.]


### 2.floor()

In [13]:
a=np.array([3.9,2.5,-1.2,7.7])
print(np.floor(a))

[ 3.  2. -2.  7.]


### 3.ceil()

In [15]:
a=np.array([3.1,2.8,-1.2,4.5])
print(np.ceil(a))

[ 4.  3. -1.  5.]


## where()

In [23]:
a=np.array([40,50,70,30,85])

# index positions
b=np.where(a>50)
print("index position:",b)
print("--"*10)
#same like if else logic
result=np.where(a>50,"pass","fail")
print(result)

index position: (array([2, 4]),)
--------------------
['fail' 'fail' 'pass' 'fail' 'pass']


## Any()

In [24]:
a=np.array([0,0,5,0])
print(np.any(a))


b=np.array([0,0,0,0])
print(np.any(b))


c=np.array([[0,0],
            [0,0]])
print(np.any(c))


d=np.array([[0,0],
            [1,0]])
print(np.any(d))

True
False
False
True
