In [2]:
import numpy as np

In [ ]:
#error-->no module numpy is defined
#pip install numpy

In [4]:
arr1=np.array([10,20,30])
print(arr1)
print(type(arr1))
#ndarray is a class/datatype

[10 20 30]
<class 'numpy.ndarray'>


In [5]:
marks=np.array([10,20,30,40,50])
marks+5

array([15, 25, 35, 45, 55])

In [6]:
marks=np.array([10,20,30,40,50])
avg=np.mean(marks)
print(avg)

30.0


In [7]:
print(np.__version__)

2.3.5


In [6]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],
              [4,5,6]])
print(arr1)
print("'-------'")
print(arr2)

[1 2 3]
'-------'
[[1 2 3]
 [4 5 6]]


In [14]:
#1d array(single dimension)--->1 index
#vector-->single dimension array
a=np.array([1,2,3,4,5])
print(a)
print("dimension:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)# it will give no of elements in a array

[1 2 3 4 5]
dimension: 1
shape: (5,)
size: 5


In [15]:
##2d array(matrix)--->2 indeces(row,coloum)
#matrix---->2 dimensional array
b=np.array([[1,2,3],
           [4,5,6]])
print(b)
print("dimension:",b.ndim)
print("shape:",b.shape)
print("size:",b.size)#it will give no of elements in a array

[[1 2 3]
 [4 5 6]]
dimension: 2
shape: (2, 3)
size: 6


In [16]:
#3d array(cube or tensor)--->3 indeces(block/depth,row,coloum)
#cube or tensor--->3dimensional array
c=np.array([[[1,2],
            [3,4]],
           
           [[5,6],
            [7,8]]])
print(c)
print("dimension:",c.ndim)
print("shape:",c.shape)# it give separately 2 rows, 2 block ,2 columns
print("size:",c.size)#it will give no of elements in a array

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension: 3
shape: (2, 2, 2)
size: 8


### numpy builtin functions

In [ ]:
#np.zeros()-->create a array filled with 0s
#np.ones()--->>create a array filled with 1s
#np.arrange-->create an array with a range of numbers
#np.linspace-->create an array with a range of numbers
#np.full-->create an array with a specific value
#np.eye-->create an array with squared identity matrix
#np.diag-->create an diagnol array  from a list or extract diagnol

In [24]:
print("zeros:\n",np.zeros((2,3)))
print("ones:\n",np.ones((2,3)))
print("arange:\n",np.arange(0,11))
print("linspace:\n",np.linspace(0,1,5))# it will generate 0 to 1 ,it will  generate 5 numbers
print("full:\n",np.full((2,2),9))
print("eye:\n",np.eye(3))
print("diag:\n",np.diag([1,2,3]))


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange:
 [ 0  1  2  3  4  5  6  7  8  9 10]
linspace:
 [0.   0.25 0.5  0.75 1.  ]
full:
 [[9 9]
 [9 9]]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diag:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## Numpy data types

In [30]:
arr=np.array([-1,-2,-3],dtype=np.int32)
print(arr)
print(arr.dtype)

[-1 -2 -3]
int32


In [29]:
arr1=np.array([1,2,3],dtype=np.uint32)
print(arr1)
print(arr1.dtype)

[1 2 3]
uint32


### float

In [31]:
arr=np.array([1.5,2.5,3.5],dtype=np.float16)
print(arr)


[1.5 2.5 3.5]


### complex

In [32]:
arr1=np.array([1+2j,2+3j,3+4j],dtype=np.complex64)
print(arr1)
print(arr1.dtype)

[1.+2.j 2.+3.j 3.+4.j]
complex64


#### boolean(bool)

In [34]:
#stores true or false
arr=np.array([True,False,True],dtype=bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


### string/unicode

In [ ]:
#stores text values
#dtype="U1"----->unicode string per element
arr=np.array(["a","b","c"],dtype="U1")
print(arr)