## insert

In [ ]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])
#arr.shape # output will in tuple
new_arr=np.insert(arr,2,99)
print(new_arr)

[10 20 99 30 40 50]


In [32]:
#2d array insert column
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_col=np.insert(arr2d,1,[99,100],axis=1)
print(new_col)
print("-------------------------")
new_col=np.insert(arr2d,1,99,axis=1)
print(new_col)

[[  1  99   2   3]
 [  4 100   5   6]]
-------------------------
[[ 1 99  2  3]
 [ 4 99  5  6]]


In [9]:
#2d array insert row
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_row=np.insert(arr2d,1,[7,8,9],axis=0)
print(new_row)
print("-------------------------")
new_row=np.insert(arr2d,1,99,axis=0)
print(new_row)
new_row=np.insert(arr2d,1,[6,8,9],axis=0)
print(new_row)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
-------------------------
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]]
[[1 2 3]
 [6 8 9]
 [4 5 6]]


## append

In [11]:
arr=np.array([1,2,3])
new_arr=np.append(arr,[4,5])
print(new_arr)

[1 2 3 4 5]


In [18]:
#2d array append row
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_row=np.append(arr2d,[[7,8,9]],axis=0)
print(new_row)
print("-------------------------")
#new_row=np.append(arr2d,99,axis=0)
#print(new_row)
new_row=np.append(arr2d,[[6,8,9]],axis=0)
print(new_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------
[[1 2 3]
 [4 5 6]
 [6 8 9]]


In [19]:
#2d array append coloum
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_col=np.append(arr2d,[[7],[8]],axis=1)
print(new_col)
print("-------------------------")
#new_row=np.insert(arr2d,1,99,axis=1)
#print(new_row)
new_col=np.append(arr2d,[[6],[8]],axis=1)
print(new_col)

[[1 2 3 7]
 [4 5 6 8]]
-------------------------
[[1 2 3 6]
 [4 5 6 8]]


## delete

In [21]:
arr=np.array([1,2,3,4,5])
new_arr=np.delete(arr,2)
print(new_arr)

[1 2 4 5]


In [23]:
#2d array delete row
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_row=np.delete(arr2d,1,axis=0)
print(new_row)
print("-------------------------")
#new_row=np.append(arr2d,99,axis=0) 
#print(new_row)
new_row=np.delete(arr2d,0,axis=0)
print(new_row)

[[1 2 3]]
-------------------------
[[4 5 6]]


In [24]:
#2d array delete coloum
arr2d=np.array([[1,2,3],
                [4,5,6]])
new_col=np.delete(arr2d,0,axis=1)
print(new_col)
print("-------------------------")
#new_row=np.insert(arr2d,1,99,axis=1)
#print(new_row)
new_col=np.delete(arr2d,1,axis=1)
print(new_col)

[[2 3]
 [5 6]]
-------------------------
[[1 3]
 [4 6]]


# array shape anipulation

## Reshape

In [28]:
arr=np.array([1,2,3,4,5,6])
arr_1=arr.reshape(2,3)
print(arr_1)
print("-------------------------")
arr_2=np.reshape(arr,(2,3))
print(arr_2)

[[1 2 3]
 [4 5 6]]
-------------------------
[[1 2 3]
 [4 5 6]]


In [29]:
# reshape 2d array
arr2d=np.array([[1,2],
                [3,4],
                [5,6]])
arr_1=arr2d.reshape(2,3)
print(arr_1)
print("-------------------------")
arr_2=np.reshape(arr2d,(2,3))
print(arr_2)

[[1 2 3]
 [4 5 6]]
-------------------------
[[1 2 3]
 [4 5 6]]


## flatten

In [30]:
arr2d=np.array([[1,2],
                [3,4],
                [5,6]])
arr_1=arr2d.flatten()
print(arr_1)

[1 2 3 4 5 6]


In [31]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr_1=arr2d.flatten()
print(arr_1)

[1 2 3 4 5 6]


## ravel()

In [33]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr_1=arr2d.ravel()
print(arr_1)

[1 2 3 4 5 6]


In [36]:
arr2d=np.array([[1,2],
                [3,4],
                [5,6]])
arr_1=arr2d.flatten()
arr_1[0]=10
print(arr_1)
print(arr2d)


[10  2  3  4  5  6]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr_1=arr2d.ravel()
arr_1[0]=10
print(arr_1)
print(arr2d)

[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [ ]:
#view()---> if new array modifies,then that modify affects/not the original array
#changes made in flatten array that will not effects the original array
#changes made in ravel array that will effects the original array
#changes made in reshape array that will effects the original array

In [38]:
arr=np.array([1,2,3,4,5,6])
arr_1=arr.reshape(2,3)
arr_1[0]=[7,8,9]
print(arr)
print("-------------------------")
print(arr_1)
print("-------------------------")
arr_2=np.reshape(arr,(2,3))
print(arr_2)

[7 8 9 4 5 6]
-------------------------
[[7 8 9]
 [4 5 6]]
-------------------------
[[7 8 9]
 [4 5 6]]


#

In [40]:
arr=np.array([[1,2,3],
                [4,5,6]])
t=arr.transpose()
print(arr)
print("-------------------------")
print(t)

[[1 2 3]
 [4 5 6]]
-------------------------
[[1 4]
 [2 5]
 [3 6]]


In [42]:
arr=np.array([[1,2,3,4,5,6],
             [7,8,9,10,11,12]])
arr_1=arr.reshape(3,4)
arr_2=arr.reshape(4,3)
arr_3=arr.ravel()
arr_4=arr.flatten()
arr_5=arr.transpose()
print("reshaped array(3,4):\n",arr_1)
print("reshaped array(4,3):\n",arr_2)
print("ravel:\n",arr_3)
print("flatten:\n",arr_4)
print("transpose:\n",arr_5)

reshaped array(3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshaped array(4,3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ravel:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
flatten:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
transpose:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


# Iterating over 1D and 2D arrays

In [46]:
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i,end=" ")

1 2 3 4 5 6 

In [47]:
#np.nditer()
arr=np.array([1,2,3,4,5,6])
for i in np.nditer(arr):
    print(i,end=" ")

1 2 3 4 5 6 

In [53]:
#2D array
arr2d=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
#row wise
for i in arr2d:
    print(i)
#elemet wise
for i in arr2d:
    for j in i:
        print(j,end=" ")
    print()

[1 2 3]
[4 5 6]
[7 8 9]
1 2 3 
4 5 6 
7 8 9 


In [54]:
arr2d=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
for i in np.nditer(arr2d):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

# operators

## arthmetic oprator

In [57]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print("addition:",a+b)
print("substraction:",a-b)
print("multiplication:",a*b)
print("division:",a/b)
print("floordivision:",a//b)
print("exponet:",a**b)
        

addition: [11 22 33]
substraction: [ 9 18 27]
multiplication: [10 40 90]
division: [10. 10. 10.]
floordivision: [10 10 10]
exponet: [   10   400 27000]


## comparision opertaor

In [58]:
a=np.array([10,20,30])
b=np.array([20,20,35])
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

[False  True False]
[ True False  True]
[False False False]
[ True False  True]
[False  True False]
[ True  True  True]
