In [5]:
import numpy as np

In [6]:
#Create a single-element NumPy array containing the value 42.
arr=np.array([42])
print(arr)

[42]


In [7]:
#Create a one-dimensional array containing the numbers 10, 20, 30, 40, and 50.
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [8]:
#Create a two-dimensional array that forms a 3×3 matrix with numbers from 1 to 9.
arr=np.array([[1,2,3],
              [3,4,5],
              [6,7,8]])
print(arr)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [12]:
#Create a three-dimensional array with shape (2, 2, 3) containing numbers from 1 to 12.
arr=np.array([[[1,2,3],
              [3,4,5]],
             [[6,7,8],
              [9,10,11]]])
print(arr)
print(arr.shape)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


### 1D array

In [13]:
arr = np.array([1, 2, 3])
print(arr.ndim)


1


### 2D array

In [14]:
arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)


2


### 3D array

In [15]:
arr = np.array([[[1, 2], [3, 4]]])
print(arr.ndim)


3


# II. Array Creation Methods


In [17]:
#Create a 3×3 matrix where all diagonal elements are 1 and the rest are 0.
arr=np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
#Create a 2×3 matrix filled entirely with zeros, another 2×3 matrix filled with ones, and a 2×3 matrix with uninitialized values [ empty ] .
print("zeros:\n",np.zeros((2,3)))
print("-------------------------")
print("ones:\n",np.ones((2,3)))
print("-------------------------")

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
-------------------------
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
-------------------------


In [22]:
#Create a 3×3 matrix where every element has the value 9.
print("full:\n",np.full((3,3),9))

full:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]


In [23]:
#Transform a one-dimensional array of 8 elements into a three-dimensional array with shape (2, 2, 2).
arr=np.array([1,2,3,4,5,6,7,8])
arr_1=arr.reshape(2,2,2)
print(arr_1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# III. Linspace & Arange Concepts

In [24]:
# Create a one-dimensional array of 5 numbers that are evenly spaced between 0 and 10, including both endpoints.
print("linspace:\n",np.linspace(0,10,5))

linspace:
 [ 0.   2.5  5.   7.5 10. ]


In [27]:
#Create a sequence of numbers starting at 0 and ending before 1, with a difference of 0.1 between consecutive numbers. Explain any floating-point issues you notice.
print("arange:\n",np.arange(0,1,0.1))

arange:
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [28]:
#Create an array of integers starting from 5 up to 20, with each number increasing by 3.
arr = np.arange(5, 21, 3)
print(arr)


[ 5  8 11 14 17 20]


In [29]:
#Create 6 numbers evenly spaced between 5 and 10, but do not include the endpoint value (10).
arr = np.linspace(5, 10, 6, endpoint=False)
print(arr)


[5.         5.83333333 6.66666667 7.5        8.33333333 9.16666667]


In [30]:
#Use np.info() on a 2D array and explore what information it provides.
arr = np.info([[1, 2], [3, 4]])
print(arr)

Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
None


# IV. Random Number Generation


In [31]:
#Create an array of 5 random whole numbers ranging from 0 to 9.
a=np.random.randint(1,10,size=5) 
print(a)

[8 3 7 1 6]


In [32]:
#Create a 2×3 array of random whole numbers ranging from 50 to 100.
a=np.random.randint(50,100,size=(2,3))
print(a)

[[69 83 56]
 [59 64 66]]


In [33]:
#You have an array of test scores: [2, 8, 12, 18, 25]. Some scores are too low and some are too high. Modify the array so that all scores less than 5 become 5, and all scores greater than 15 become 15.
scores = np.array([2, 8, 12, 18, 25])

pscores[scores < 5] = 5
scores[scores > 15] = 15

print(scores)


[ 5  8 12 15 15]


In [37]:
#You are given the following exam scores: [10, 20, 20, 30, 40, 50] Calculate the mean, median, variance, and standard deviation of the scores.
import statistics as st
marks=[10, 20, 20, 30, 40, 50] 
mean_value=st.mean(marks)
mode_value=st.mode(marks)
median_value=st.median(marks)
print("mean:",mean_value)
print("mode:",mode_value)
print("median:",median_value)


mean: 28.333333333333332
mode: 20
median: 25.0


# V. Array Attributes: Shape, Size, Memory


In [40]:
#Find the shape, total number of elements, and number of dimensions of an array.
arr=np.array([[1,2,3],
              [3,4,5],
              [6,7,8]])
print(arr.shape)
print(arr.size)
print(arr.ndim)


(3, 3)
9
2


In [42]:
#For the array [[1,2,3],[4,5,6]], find its shape.
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


#Determine how many bytes each element of an array uses.
Data Type	Bytes
int32	      4
int64	      8
float32   	  4
float64	      8

#Explain how total memory used by an array relates to the element size and number of elements.
The array has 6 elements
Each element uses 8 bytes (int64)
Total memory = 6 × 8 = 48 bytes

#For an array of three 32-bit integers, calculate the total memory in bytes.
The array has 6 elements
Each element uses 4 bytes (int32)
Total memory = 6 × 4 = 24 bytes

For a 3×3 array of 64-bit floating-point numbers, calculate its memory usage in bytes.
The array has 9 lements
Each element uses 8 bytes (float)
Total memory = 9× 8= 72 bytes

# VI. List vs Array


Explain the differences between Python lists and NumPy arrays in terms of memory, operations, and performance.
| Aspect      | Python Lists                   NumPy Arrays                  |
| ----------- | -----------------------------| ------------------------------|
| Memory      | High (per-object overhead)   | Low (contiguous, fixed dtype) |
| Operations  | General, no vectorization    | Vectorized math, broadcasting |
| Performance | Slow for numerics            | Fast (10-100x) for arrays     |



In [45]:
#Multiply a Python list and a NumPy array by 2. Compare the results.
li=[1,2,3,4]
print(li*2)
arr = np.arange(5, 21, 3)
print(arr*2)

[1, 2, 3, 4, 1, 2, 3, 4]
[10 16 22 28 34 40]


In [52]:
#Add two Python lists and then add two NumPy arrays of the same numbers. Compare the results
li=[1,2,3,4]
li1=[5,6,7,8]
print(li+li1)
arr=np.array([1,2,3,4])
arr1=np.array([5,6,3,4])
v=arr+arr1
print(v)

[1, 2, 3, 4, 5, 6, 7, 8]
[6 8 6 8]


In [53]:
#Convert a Python list [10, 20, 30, 40] into a NumPy array and multiply each element by 2.
arr=np.array([10, 20, 30, 40])
v=arr*2
print(v)

[20 40 60 80]


#Explain why NumPy arrays are stored in contiguous blocks of memory and why this is important.
NumPy arrays are stored in contiguous blocks of memory to enable efficient data handling and computation.

Storage Mechanism
NumPy allocates a single, continuous chunk of memory for an array's data buffer, where elements of a uniform data type (dtype) are placed sequentially without gaps or pointers between them. This contrasts with Python lists, which store references to separate objects scattered in memory. Arrays can be C-contiguous (row-major order, default) or F-contiguous (column-major), but both maintain adjacency for their respective traversal patterns.




# VII. Indexing & Slicing


In [54]:
#From a 1D arrayFrom a 1D array [10, 20, 30, 40, 50], extract the 2nd and 4th element
arr=np.array( [10, 20, 30, 40, 50])
print(arr[[2,4]])

[30 50]


In [58]:
#From a 2D array, access the element in the first row and second column
arr = np.array([[1, 2], [3, 4]])
print(arr[0])
print(arr[:,1])


[1 2]
[2 4]


Explain the difference between selecting elements by index and selecting elements by a condition (boolean indexing).

Indexing by index and boolean indexing in NumPy arrays select elements differently: the former uses specific positions, while the latter filters based on conditions.

Index Selection
Index selection accesses elements at exact integer positions, like arr[2] for the third item or arr[1:4] for a slice. It requires knowing positions upfront and returns a view or copy of those specific locations. This works for single values, slices, or lists of indices (fancy indexing).

Boolean Indexing
Boolean indexing uses a matching boolean array (or condition) where True selects the element and False skips it, e.g., arr[arr > 5] picks all values greater than 5. NumPy broadcasts the mask across dimensions if needed, flattening results into a new array of selected elements. It's vectorized for conditions like arr[(arr > 3) & (arr < 7)

In [63]:
#From an array [3, 7, 2, 9, 5, 10], select only the elements that are greater than 5.
arr=np.array([3, 7, 2, 9, 5, 10])
v=arr[arr>5]
print(v)

[ 7  9 10]


In [64]:
arr = np.array([10, 20, 30, 40, 50, 60])
selected = arr[::2]
print(selected) 


[10 30 50]


In [65]:
#Replace all negative numbers in [1, -2, 3, -4, 5] with zero.
arr = np.array( [1, -2, 3, -4, 5])
arr[arr<=0]=0
print(arr)

[1 0 3 0 5]


Explain whether creating a sub-array using slicing creates a view of the original array or a copy.
NumPy slicing typically creates a view of the original array, not a copy, to save memory and time.

View Behavior
Basic slicing (e.g., arr[1:3], arr[::2], or arr[:, 1]) produces a view that references the same underlying data buffer. Changes to the sliced array affect the original, like sliced[0] = 99 updating arr. This works because slices maintain contiguous memory strides when possible.

# VIII. Data Types and Numeric Precision


#Explain the differences between 8-bit, 16-bit, and 32-bit integers.
| Type   | Bytes | Signed Range      | Unsigned Range |
| ------ | ----- | ----------------- | -------------- |
| 8-bit  | 1     | -128 to 127       | 0 to 255       |
| 16-bit | 2     | -32,768 to 32,767 | 0 to 65,535    |
| 32-bit | 4     | -2B to 2B         | 0 to 4B        |

Explain the differences between 16-bit and 64-bit floating-point numbers.
| Aspect    | 16-bit (FP16)            | 64-bit (FP64)                     |
| --------- | ------------------------ | --------------------------------- |
| Bits      | 16 (1+5+10) exxactcorp​  | 64 (1+11+52) exxactcorp​          |
| Precision | ~3-4 digits exxactcorp​  | ~15-17 digits exxactcorp​         |
| Range     | ±65,504 exxactcorp​      | ±1.8e308 exxactcorp​              |
| Memory    | Low, fast ML exxactcorp​ | High, precise science exxactcorp​ |

In [66]:
#Create an array of 5 floating-point numbers stored with 32-bit precision
arr = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float32)
print(arr)
print(arr.dtype) 


[1.1 2.2 3.3 4.4 5.5]
float32


#Dividing two NumPy arrays of 8-bit integers (int8 or uint8) results in a float64 array due to NumPy's type promotion rules for division.
​

Result Type
The / operator promotes integer division to floating-point to preserve fractional results and avoid truncation. For int8 arrays, the output dtype is always float64 (double precision), regardless of input size.

What is the most suitable data type for storing RGB pixel values (0–255)?

uint8 (8-bit unsigned integer) is the most suitable data type for storing RGB pixel values in the range 0–255.

Why uint8?
Each RGB channel fits perfectly in uint8, which stores integers from 0 to 255 using just 1 byte per channel (3 bytes per pixel). This is the standard for image formats (JPEG, PNG) and libraries like PIL, OpenCV, and matplotlib expect this dtype for pixel data.

Memory Efficiency
A 1920×1080 RGB image uses 6.2 MB with uint8 vs. 12.4 MB with float32 or 24.8 MB with float64. No precision loss since pixels are inherently 8-bit integers.

In [69]:
#Convert an array of integers to floating-point numbers.
arr=np.array( [10, 20, 30, 40, 50])
new_arr=arr.astype(np.float64)
print(new_arr)

[10. 20. 30. 40. 50.]


In [70]:
#Convert a 32-bit floating-point array [1.5, 2.5, 3.5] to 16-bit integers and describe what happens
arr=np.array([1.5, 2.5, 3.5])
new_arr=arr.astype(np.int16)
print(new_arr)


[1 2 3]


In [71]:
#Assign a floating-point number to an integer array element. Describe the result.
arr = np.array([1, 2, 3], dtype=np.int32)
arr[1] = 4.9
print(arr)      
print(arr.dtype) 


[1 4 3]
int32


# IX. Mixed Data Type & Casting Scenarios


In [72]:
#Create an array containing [1, 2.5, True, '3'] and describe what data type the array elements become.
arr = np.array([1, 2.5, True, '3'])
print(arr.dtype)

<U32


In [73]:
#If an array contains both integers and floating-point numbers, what data type is assigned?
arr = np.array([1, 2.5,3])
print(arr.dtype)

float64


#Why is 64-bit floating-point preferred for calculations over 16-bit floating-poin
64-bit floating-point (FP64) is preferred over 16-bit (FP16) for most calculations due to vastly superior precision and numerical stability

In [74]:
#Convert [1, 0, 3, 0, 5] into a boolean array and describe the output.
arr=np.array([1, 0, 3, 0, 5] ,dtype=bool)
print(arr)



[ True False  True False  True]


#Explain the role of specifying the data type when creating an array.
Specifying the data type (dtype) when creating a NumPy array gives precise control over storage format, memory usage, and computation behavior.

# X. Exploring Documentation


### Explore the NumPy documentation and learn about all the array methods and functions that we have studied in class so far. Write a short note on what each method does and how it can be used.

Specifying dtype during array creation and various indexing methods are key NumPy concepts from class discussions and documentation.

Array Creation with dtype
dtype sets element type (e.g., np.uint8, np.float32), controlling memory, precision, and operations. Use via np.array(data, dtype=np.int32) to optimize storage (e.g., RGB pixels as uint8) and prevent promotion (e.g., int division stays int).

Basic Indexing
Accesses single elements (arr[2]) or subarrays by integer positions (0-based, negative from end). Returns scalar or view; e.g., arr[1:4] selects indices 1-3.

Slicing
Extracts contiguous ranges with arr[start:stop:step] (defaults: start=0, stop=len, step=1). Always creates views for efficiency; e.g., arr[::2] every other element. Negative step reverses.

Boolean Indexing
Filters via condition mask (arr[arr > 5]), returning flattened copy of matching elements. Vectorized; e.g., arr[(arr > 3) & (arr < 7)]. Shape matches True count.

Fancy Indexing
Uses integer arrays (arr[[0,2,4]]) or multi-dim indices for arbitrary selection, always creating copies. Broadcasting applies; combines with slices.

Views vs Copies
Basic slicing yields views (shared memory, changes propagate); fancy/boolean yield copies. Check with arr.base; use .copy() for explicit copy