In [3]:
import numpy as np

In [5]:
#1️⃣ Integer Indexing & Negative Indexing
#Input
A = np.array([100, 200, 300, 400, 500])
print("First two elements:",A[0:2])
print("Last three elements:",A[2:])
print("Middle element:",A[2])

First two elements: [100 200]
Last three elements: [300 400 500]
Middle element: 300


In [7]:
#2️⃣ Slicing (Exclude First & Last)
#Input
#A = np.array([2, 4, 6, 8, 10, 12, 14])
#Expected Output
#[4, 6, 8, 10, 12]
A = np.array([2, 4, 6, 8, 10, 12, 14])
print("Last  elements:",A[1:-1])

Last  elements: [ 4  6  8 10 12]


In [15]:
#3️⃣ 2D Array Indexing & Slicing
#Input
#M = np.array([
 #   [10, 20, 30, 40],
  #  [50, 60, 70, 80],
   # [90, 100, 110, 120]
#])

#Expected Output
#Sub-matrix        → [[20, 30],
 #                    [60, 70]]

#Last row          → [90, 100, 110, 120]

#First column      → [10, 50, 90]
M = np.array([
    [10, 20, 30, 40],
   [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print("Sub-matrix:",M[0:2,1:3])
print("Last row:",M[2,:])
print("First column:",M[:,0])


Sub-matrix: [[20 30]
 [60 70]]
Last row: [ 90 100 110 120]
First column: [10 50 90]


In [17]:
#4️⃣ Step Slicing
#Input
#A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
#Expected Output
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(A[::3])

[1 4 7]


# 🔹 Part B: Boolean Indexing


In [20]:
#5️⃣ Condition-Based Filtering
#Input
#A = np.array([5, 12, 17, 3, 8, 20])

#Expected Output
#Values > 10        → [12, 17, 20]
#Values ≤ 8         → [5, 3, 8]
A = np.array([5, 12, 17, 3, 8, 20])
con=A>10
print(A[con])
con1=A<=8
print(A[con1])


[12 17 20]
[5 3 8]


In [24]:
#6️⃣ Multiple Boolean Conditions
#Input
#A = np.array([10, 15, 20, 25, 30, 35])

#Expected Output
#[20, 25, 30, 35]
A = np.array([10, 15, 20, 25, 30, 35])
con=A>15
print(A[con])

[20 25 30 35]


In [26]:
#7️⃣ Boolean Filtering + Counting
#Input
#A = np.array([3, -2, 0, 5, -7, 8])

#Expected Output
#Non-negative values → [3, 0, 5, 8]
#Negative count      → 2
A = np.array([3, -2, 0, 5, -7, 8])
con=A>0
print("Non-negative values:",A[con])
negative_sum=np.sum(A < 0)
print("Non-negative values:",negative_sum)

Non-negative values: [3 5 8]
Non-negative values: 2


In [29]:
#8️⃣ Boolean Replacement
#Input
#A = np.array([1, 2, 3, 4, 5, 6, 7])

#Expected Output
#[-1, 2, -1, 4, -1, 6, -1]
arr= np.array([1, 2, 3, 4, 5, 6, 7])
arr[[0,2,4,6]]=[-1]
print(arr)


[-1  2 -1  4 -1  6 -1]


# 🔹 Part C: Fancy Indexing


In [32]:
#9️⃣ Index List Selection
#Input
#A = np.array([11, 22, 33, 44, 55, 66])

#Expected Output
#[22, 44, 66]
arr= np.array([11, 22, 33, 44, 55, 66])
ind=arr[[1,3,5]]
print(ind)


[22 44 66]


In [33]:
##🔟 Rearranging Elements
#Input
#A = np.array([100, 200, 300, 400, 500])

#Expected Output
#[500, 300, 100]
A = np.array([100, 200, 300, 400, 500])
ind=A[[-1,-3,-5]]
print(ind)

[500 300 100]


In [34]:
#1️⃣1️⃣ Fancy Indexing on 2D Array
#Input
#M = np.array([
 #   [1, 2, 3],
  #  [4, 5, 6],
   # [7, 8, 9]
#])

#Expected Output
#[1, 5, 9]
M = np.array([
    [1, 2, 3],S
    [4, 5, 6],
    [7, 8, 9]
])
result = np.diagonal(M)
print(result)

[1 5 9]


In [36]:
#1️⃣2️⃣ Row Reordering
#Input
#M = same as above

#Expected Output
#[[7, 8, 9],
 #[1, 2, 3]]
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(M[2,:])
print(M[0,:])


[7 8 9]
[1 2 3]


# 🔹 Part D: Boolean Indexing vs np.where()


In [38]:
#1️⃣3️⃣ Filtering vs Transforming
#Input

#Expected Output
#Boolean indexing → [9, 7, 12]
#np.where         → [0, 1, 0, 1, 1, 0]
A = np.array([4, 9, 2, 7, 12, 3])
odd_values = A[A % 2 != 0]
print("Boolean indexing →", odd_values)
mask = np.where(A % 2 != 0, 1, 0)
print("np.where         →", mask)

Boolean indexing → [9 7 3]
np.where         → [0 1 0 1 0 1]


In [42]:
#1️⃣4️⃣ Replace Negatives (Two Methods)
#Input
#A = np.array([-5, 10, -3, 8, -1])

#Expected Output
#[0, 10, 0, 8, 0]
A = np.array([-5, 10, -3, 8, -1])
mask = np.where(A>0,A,0)
print("np.wher→", mask)

np.wher→ [ 0 10  0  8  0]


In [47]:
#1️⃣5️⃣ Labeling Data with np.where()
#nput
#scores = np.array([45, 60, 30, 85, 90])

#Expected Output
#Filtered scores → [60, 85, 90]
#Labels          → ["Fail", "Pass", "Fail", "Pass", "Pass"]
A= np.array([45, 60, 30, 85, 90])
con=A>50
print("Filtered scores:",A[con])
labels = np.where(A >= 50, "Pass", "Fail")
print("labels:",labels)

Filtered scores: [60 85 90]
labels: ['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


# 🔹 Part E: Broadcasting


In [53]:
#1️⃣6️⃣ Row-wise Broadcasting
#Input
#M = np.array([[1, 2, 3],
               #[4, 5, 6]])
#A = np.array([10, 20, 30])

#Addition     → [[11, 22, 33],
                #[14, 25, 36]]

#Subtraction  → [[-9, -18, -27],
               # [-6, -15, -24]]
M = np.array([[1, 2, 3],
              [4, 5, 6]])
A = np.array([10, 20, 30])
print("Addition:",M+A)
print("--"*10)
print("subtraction:",M-A)


Addition: [[11 22 33]
 [14 25 36]]
--------------------
subtraction: [[ -9 -18 -27]
 [ -6 -15 -24]]


In [57]:
#1️⃣7️⃣ Row Normalization
#nput
#M = np.array([[2, 4],
 #             [6, 8]])

#Expected Output
#[[1, 2],
#[3, 4]]


M = np.array([[2, 4],
            [6, 8]])

row_normalized = M / M[:, [0]]
print(row_normalized)


[[1.         2.        ]
 [1.         1.33333333]]


In [58]:
#1️⃣8️⃣ Scalar Broadcasting
#Input
#A = np.array([10, 20, 30])

#Expected Output
#[15, 25, 35]
A = np.array([10, 20, 30])
print(A+5)

[15 25 35]


In [59]:
#1️⃣9️⃣ Boolean vs np.where() on 2D
#Input
#M = np.array([[5, 10, 15],
 #             [20, 25, 30]])

#Expected Output
#[[5, 10, 15],
 #[20, 20, 20]]

M = np.array([[5, 10, 15],
              [20, 25, 30]])

result_where = np.where(M > 20, 20, M)
print(result_where)



[[ 5 10 15]
 [20 20 20]]


In [62]:
#2️⃣0️⃣ Broadcasting Concept Check
#Input
#M = np.array([[1, 2],
              #[3, 4],
             # [#5, 6]])
#A = np.array([10, 20])

#Expected Output
#[[11, 22],
# [13, 24],
# [15, 26]]
M = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A = np.array([10, 20])

result = M + A
print(result)


[[11 22]
 [13 24]
 [15 26]]
