# statistics

## mean()

In [1]:
import numpy as np

In [2]:
arr=np.array([50,70,30,90,60])
average=np.mean(arr)
print("mean value:",average)

mean value: 60.0


In [5]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
print("mean of all  values:",np.mean(arr2d))
print("mean of each row:",np.mean(arr2d,axis=0))
print("mean of each column:",np.mean(arr2d,axis=1))

mean of all  values: 3.5
mean of each row: [2.5 3.5 4.5]
mean of each column: [2. 5.]


## median()

In [6]:
arr=np.array([50,70,30,90,60])
med=np.median(arr)
print("median value:",med)

median value: 60.0


In [7]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
print("median of all  values:",np.median(arr2d))
print("median of each row:",np.median(arr2d,axis=0))
print("median of each column:",np.median(arr2d,axis=1))

median of all  values: 3.5
median of each row: [2.5 3.5 4.5]
median of each column: [2. 5.]


## varience()

In [8]:
marks=np.array([50,70,30,90,60])
print("varience:",np.var(marks))

varience: 400.0


In [10]:
marks=np.array([[1,2,3],
                [4,5,6]])
print("varience:",np.var(marks))
print("varience of each row:",np.var(marks,axis=0))
print("varienceof each column:",np.var(marks,axis=1))

varience: 2.9166666666666665
varience of each row: [2.25 2.25 2.25]
varienceof each column: [0.66666667 0.66666667]


## standard devition

In [12]:
marks=np.array([50,70,30,90,60])
print("standad devition:",np.std(marks))

standad devition: 20.0


In [13]:
marks=np.array([[1,2,3],
                [4,5,6]])
print("standad devition:",np.std(marks))
print("standad devition of each row :",np.std(marks,axis=0))
print("standad devition of each column:",np.std(marks,axis=1))

standad devition: 1.707825127659933
standad devition of each row : [1.5 1.5 1.5]
standad devition of each column: [0.81649658 0.81649658]


## co-relation co-efficient

In [23]:
#positive
x=[1,2,3,4,5]
y=[2,4,6,8,10]
corr=np.corrcoef(x,y)
print(corr)
print("--------------")
#negative correlation
x1=[1,2,3,4,5]
y1=[10,8,6,4,2]
corr1=np.corrcoef(x1,y1)
print(corr1)

[[1. 1.]
 [1. 1.]]
--------------
[[ 1. -1.]
 [-1.  1.]]


# vectorizatinon

In [25]:
# without numpy
marks=[50,70,30,90,60]
updated_marks=[x+5 for x in marks]
print(updated_marks)

[55, 75, 35, 95, 65]


In [26]:
#with numpy
marks=np.array([50,70,30,90,60])
updated_marks=marks+5
print(updated_marks)

[55 75 35 95 65]


In [27]:
a=[1,2,3]
b=[4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [28]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


# Array manipulation

## concatenation()

In [31]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [38]:
a=np.array([[1,2,3],
         [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])
c=np.concatenate((a,b))
print(c)
print("--------------")
#row wise
row_con=np.concatenate((a,b),axis=0)
print(row_con)
print("--------------")
#column wise
col_con=np.concatenate((a,b),axis=1)
print(col_con)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## stack()

### vstack()

In [40]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [41]:
a=np.array([[1,2,3],
         [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])
c=np.vstack((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Hstack()

In [42]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [43]:
a=np.array([[1,2,3],
         [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])
c=np.hstack((a,b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### column stack()

In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.column_stack((a,b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
a=np.array([[1,2,3],
         [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])
c=np.column_stack((a,b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## split()

# hsplit()

In [64]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
c=np.hsplit(a,2)
print(c)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [65]:
split_4=np.hsplit(a,4)
print(split_4)

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


### vsplit()

In [69]:
a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12],
           [13,14,15,16]])
c=np.vsplit(a,4)
print(c)
print("-"*20)
d=np.vsplit(a,2)
print(d)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]
--------------------
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


## sorting()

In [73]:
arr=np.array([5,1,4,3,2])
sorted_arr=np.sort(arr)
print("accending order:",sorted_arr)
print("decending order:",sorted_arr[::-1])

accending order: [1 2 3 4 5]
decending order: [5 4 3 2 1]


In [2]:
import numpy as np
a=np.array([[3,1,4],
            [5,6,2]])
sorted_arr=np.sort(a)
print("accending order:",sorted_arr)
print("decending order:",sorted_arr[::-1])

accending order: [[1 3 4]
 [2 5 6]]
decending order: [[2 5 6]
 [1 3 4]]


## arg sort()

In [5]:
marks=np.array([40,10,30,20])   # index position=[0,1,2,3]
sorted_marks=np.sort(marks)
sorted_indices=np.argsort(marks )#--->it gives index postions
print("original:",marks)
print("sorted values:",sorted_marks)
print("argsorted values:",sorted_indices)

original: [40 10 30 20]
sorted values: [10 20 30 40]
argsorted values: [1 3 2 0]


In [ ]:
a=np.array([[3,1,4],
            [5,6,2]])
print("argsorted column values:\n",np.argsort((a,axis=0))
print("argsorted row values:\n",np.argsort((a,axis=1))